package Vistas;

import Controladores.ControladorBalanceGeneral;
import Controladores.ControladorBalanzaC;
import Controladores.ControladorContable;
import Controladores.ControladorEstadoResultado;
import Controladores.ControladorLibroDiario;
import java.sql.SQLException;
import Controladores.ControladorLibroMayor;

import Controladores.ControladorLogin;

import Controladores.ControladorMostrarLibroDiario;
import Utilidades.VistaAcercaDe;
import utilidades.BackupDatabase;
import utilidades.RestoreBackupDatabase;
import Vistas.VistaBalanceGenerales;
import Vistas.VistaBalanzaComprobacion;
import Vistas.VistaLibroDiario;
import Vistas.VistaMostrarLibroDiario;
import vistas.VistaSalir;
import vistas.Catalogos;
import vistas.VistaEstadoResultado;
import vistas.AgregarCatalogo;
import vistas.AgregarSubcuenta;

import Vistas.VistaMayor;

import controladores.ControladorMostrarCatalogo;

import Vistas.Login;
import controladores.ControladorAgregarCatalogo;
import controladores.ControladorMostrarCatalogo;
import controladores.ControladorSubCuenta;

import utilidades.Fondo;
import java.awt.Color;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import modelos.BalanceGeneral;

public class Dashboard extends javax.swing.JFrame {

    boolean visible = false;

    Color colorDefaultModulo,
            colorActivoModulo,
            colorDefaultOp,
            colorActivoOp,
            colorMenuLateral,
            colorFuente,
            colorFuente2;

    public Dashboard() {
        initComponents();
        setImageLabel(logo, "src/img/minerva.png");
//        setImageLabel(home, "src/img/cargando.gif");
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        color();
        config();
        ocultarMod(0);
        panels();
        

    }

    public void iniciar() {
        this.setVisible(true);
    }

    //Método para colocar el tamaño ""X""
    public void setImageLabel(JLabel log, String root) {
        ImageIcon image = new ImageIcon(root);
        Icon icon = new ImageIcon(
                image.getImage().getScaledInstance(log.getWidth(), log.getHeight(), Image.SCALE_DEFAULT));
        log.setIcon(icon);
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        menuLateral = new javax.swing.JPanel();
        panelOp1 = new javax.swing.JPanel();
        VerCatalogo = new javax.swing.JLabel();
        AgregarMayor = new javax.swing.JLabel();
        AgregarSub = new javax.swing.JLabel();
        panelOp2 = new javax.swing.JPanel();
        menu2Op1 = new javax.swing.JLabel();
        menu2Op2 = new javax.swing.JLabel();
        panelOp3 = new javax.swing.JPanel();
        menu3Op1 = new javax.swing.JLabel();
        menu3Op2 = new javax.swing.JLabel();
        menu3Op3 = new javax.swing.JLabel();
        menu3Op4 = new javax.swing.JLabel();
        panelOp4 = new javax.swing.JPanel();
        menu4Op1 = new javax.swing.JLabel();
        menu4Op2 = new javax.swing.JLabel();
        menu4Op3 = new javax.swing.JLabel();
        panelOp6 = new javax.swing.JPanel();
        menu6Op2 = new javax.swing.JLabel();
        menu6Op1 = new javax.swing.JLabel();
        lbSistemasContables = new javax.swing.JLabel();
        opMenu1Catalogo = new javax.swing.JLabel();
        opMenu2LibroDiario = new javax.swing.JLabel();
        opMenu3Reportes = new javax.swing.JLabel();
        opMenu4Cierre = new javax.swing.JLabel();
        opMenu6 = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        opMenu5AcercaDe = new javax.swing.JLabel();
        panelOp5 = new javax.swing.JPanel();
        menu5Op1 = new javax.swing.JLabel();
        panelTop = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        escritorio = new javax.swing.JDesktopPane();
        panelCopyR = new javax.swing.JPanel();
        lbCopyR = new javax.swing.JLabel();
        rSLabelFecha2 = new rojeru_san.RSLabelFecha();
        rSLabelHora2 = new rojeru_san.RSLabelHora();
        jLabel3 = new javax.swing.JLabel();
        panelSalir = new javax.swing.JPanel();
        opSalir = new javax.swing.JLabel();
        lbBienvenida = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sistemas Contables");
        setUndecorated(true);

        menuLateral.setForeground(new java.awt.Color(255, 255, 255));

        panelOp1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelOp1MousePressed(evt);
            }
        });

        VerCatalogo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        VerCatalogo.setForeground(new java.awt.Color(255, 255, 255));
        VerCatalogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N
        VerCatalogo.setText("Ver Catalago");
        VerCatalogo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        VerCatalogo.setOpaque(true);
        VerCatalogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                VerCatalogoMousePressed(evt);
            }
        });

        AgregarMayor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AgregarMayor.setForeground(new java.awt.Color(255, 255, 255));
        AgregarMayor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N
        AgregarMayor.setText("Agregar Cuenta Mayor");
        AgregarMayor.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        AgregarMayor.setOpaque(true);
        AgregarMayor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AgregarMayorMousePressed(evt);
            }
        });

        AgregarSub.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AgregarSub.setForeground(new java.awt.Color(255, 255, 255));
        AgregarSub.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N
        AgregarSub.setText("Agregar SubCuenta");
        AgregarSub.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        AgregarSub.setOpaque(true);
        AgregarSub.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AgregarSubMousePressed(evt);
            }
        });

        javax.swing.GroupLayout panelOp1Layout = new javax.swing.GroupLayout(panelOp1);
        panelOp1.setLayout(panelOp1Layout);
        panelOp1Layout.setHorizontalGroup(
            panelOp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOp1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(panelOp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AgregarMayor, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                    .addGroup(panelOp1Layout.createSequentialGroup()
                        .addGroup(panelOp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AgregarSub, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(VerCatalogo, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelOp1Layout.setVerticalGroup(
            panelOp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOp1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(VerCatalogo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AgregarMayor, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AgregarSub, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelOp2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelOp2MousePressed(evt);
            }
        });

        menu2Op1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        menu2Op1.setForeground(new java.awt.Color(255, 255, 255));
        menu2Op1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N
        menu2Op1.setText("Ingresar Libro Diario");
        menu2Op1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menu2Op1.setOpaque(true);
        menu2Op1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menu2Op1MousePressed(evt);
            }
        });

        menu2Op2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        menu2Op2.setForeground(new java.awt.Color(255, 255, 255));
        menu2Op2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N
        menu2Op2.setText("Ver Libro Diario");
        menu2Op2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menu2Op2.setOpaque(true);
        menu2Op2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menu2Op2MousePressed(evt);
            }
        });

        javax.swing.GroupLayout panelOp2Layout = new javax.swing.GroupLayout(panelOp2);
        panelOp2.setLayout(panelOp2Layout);
        panelOp2Layout.setHorizontalGroup(
            panelOp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOp2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(panelOp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(menu2Op2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menu2Op1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        panelOp2Layout.setVerticalGroup(
            panelOp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOp2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menu2Op1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menu2Op2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelOp3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelOp3MousePressed(evt);
            }
        });

        menu3Op1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        menu3Op1.setForeground(new java.awt.Color(255, 255, 255));
        menu3Op1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N
        menu3Op1.setText("Balanza Comprobacion");
        menu3Op1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menu3Op1.setOpaque(true);
        menu3Op1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menu3Op1MousePressed(evt);
            }
        });

        menu3Op2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        menu3Op2.setForeground(new java.awt.Color(255, 255, 255));
        menu3Op2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N
        menu3Op2.setText("Balance General");
        menu3Op2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menu3Op2.setOpaque(true);
        menu3Op2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menu3Op2MousePressed(evt);
            }
        });

        menu3Op3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        menu3Op3.setForeground(new java.awt.Color(255, 255, 255));
        menu3Op3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N
        menu3Op3.setText("Estado de Resultado");
        menu3Op3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menu3Op3.setOpaque(true);
        menu3Op3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menu3Op3MousePressed(evt);
            }
        });

        menu3Op4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        menu3Op4.setForeground(new java.awt.Color(255, 255, 255));
        menu3Op4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N
        menu3Op4.setText("Libro Mayor");
        menu3Op4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menu3Op4.setOpaque(true);
        menu3Op4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menu3Op4MousePressed(evt);
            }
        });

        javax.swing.GroupLayout panelOp3Layout = new javax.swing.GroupLayout(panelOp3);
        panelOp3.setLayout(panelOp3Layout);
        panelOp3Layout.setHorizontalGroup(
            panelOp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOp3Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(panelOp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menu3Op1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menu3Op3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menu3Op2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menu3Op4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        panelOp3Layout.setVerticalGroup(
            panelOp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOp3Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(menu3Op4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menu3Op1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menu3Op3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menu3Op2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        panelOp4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelOp4MousePressed(evt);
            }
        });

        menu4Op1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        menu4Op1.setForeground(new java.awt.Color(255, 255, 255));
        menu4Op1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N
        menu4Op1.setText("Generar Ajuste de IVA");
        menu4Op1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menu4Op1.setOpaque(true);
        menu4Op1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menu4Op1MousePressed(evt);
            }
        });

        menu4Op2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        menu4Op2.setForeground(new java.awt.Color(255, 255, 255));
        menu4Op2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N
        menu4Op2.setText("Generar Partidas de Ajuste");
        menu4Op2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menu4Op2.setOpaque(true);
        menu4Op2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menu4Op2MousePressed(evt);
            }
        });

        menu4Op3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        menu4Op3.setForeground(new java.awt.Color(255, 255, 255));
        menu4Op3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N
        menu4Op3.setText("Nuevo Ciclo Contable");
        menu4Op3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menu4Op3.setOpaque(true);
        menu4Op3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menu4Op3MousePressed(evt);
            }
        });

        javax.swing.GroupLayout panelOp4Layout = new javax.swing.GroupLayout(panelOp4);
        panelOp4.setLayout(panelOp4Layout);
        panelOp4Layout.setHorizontalGroup(
            panelOp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOp4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelOp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menu4Op1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelOp4Layout.createSequentialGroup()
                        .addGroup(panelOp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(menu4Op2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(menu4Op3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        panelOp4Layout.setVerticalGroup(
            panelOp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOp4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menu4Op1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(menu4Op2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menu4Op3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        panelOp6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelOp6MousePressed(evt);
            }
        });

        menu6Op2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        menu6Op2.setForeground(new java.awt.Color(255, 255, 255));
        menu6Op2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N
        menu6Op2.setText("Generar Backup ");
        menu6Op2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menu6Op2.setOpaque(true);
        menu6Op2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menu6Op2MousePressed(evt);
            }
        });

        menu6Op1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        menu6Op1.setForeground(new java.awt.Color(255, 255, 255));
        menu6Op1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N
        menu6Op1.setText("Restore Backup");
        menu6Op1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menu6Op1.setOpaque(true);
        menu6Op1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menu6Op1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout panelOp6Layout = new javax.swing.GroupLayout(panelOp6);
        panelOp6.setLayout(panelOp6Layout);
        panelOp6Layout.setHorizontalGroup(
            panelOp6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOp6Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(panelOp6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menu6Op1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelOp6Layout.createSequentialGroup()
                        .addComponent(menu6Op2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 1, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelOp6Layout.setVerticalGroup(
            panelOp6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOp6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menu6Op2, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menu6Op1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        lbSistemasContables.setBackground(new java.awt.Color(204, 204, 204));
        lbSistemasContables.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbSistemasContables.setForeground(new java.awt.Color(255, 255, 255));
        lbSistemasContables.setText(".");

        opMenu1Catalogo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        opMenu1Catalogo.setForeground(new java.awt.Color(0, 51, 153));
        opMenu1Catalogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N
        opMenu1Catalogo.setText("Catalogo");
        opMenu1Catalogo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        opMenu1Catalogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                opMenu1CatalogoMousePressed(evt);
            }
        });

        opMenu2LibroDiario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        opMenu2LibroDiario.setForeground(new java.awt.Color(0, 51, 153));
        opMenu2LibroDiario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N
        opMenu2LibroDiario.setText("Libro Diario");
        opMenu2LibroDiario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        opMenu2LibroDiario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                opMenu2LibroDiarioMousePressed(evt);
            }
        });

        opMenu3Reportes.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        opMenu3Reportes.setForeground(new java.awt.Color(0, 51, 153));
        opMenu3Reportes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N
        opMenu3Reportes.setText("Reportes");
        opMenu3Reportes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        opMenu3Reportes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                opMenu3ReportesMousePressed(evt);
            }
        });

        opMenu4Cierre.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        opMenu4Cierre.setForeground(new java.awt.Color(0, 51, 153));
        opMenu4Cierre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N
        opMenu4Cierre.setText("Cierre");
        opMenu4Cierre.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        opMenu4Cierre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                opMenu4CierreMousePressed(evt);
            }
        });

        opMenu6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        opMenu6.setForeground(new java.awt.Color(0, 51, 153));
        opMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N
        opMenu6.setText("Backup o Restore BD");
        opMenu6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        opMenu6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                opMenu6MousePressed(evt);
            }
        });

        opMenu5AcercaDe.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        opMenu5AcercaDe.setForeground(new java.awt.Color(0, 51, 153));
        opMenu5AcercaDe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N
        opMenu5AcercaDe.setText("Acerca de");
        opMenu5AcercaDe.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        opMenu5AcercaDe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                opMenu5AcercaDeMousePressed(evt);
            }
        });

        panelOp5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelOp5MousePressed(evt);
            }
        });

        menu5Op1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        menu5Op1.setForeground(new java.awt.Color(255, 255, 255));
        menu5Op1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N
        menu5Op1.setText("Ver");
        menu5Op1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menu5Op1.setOpaque(true);
        menu5Op1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menu5Op1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout panelOp5Layout = new javax.swing.GroupLayout(panelOp5);
        panelOp5.setLayout(panelOp5Layout);
        panelOp5Layout.setHorizontalGroup(
            panelOp5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOp5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(menu5Op1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        panelOp5Layout.setVerticalGroup(
            panelOp5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOp5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menu5Op1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout menuLateralLayout = new javax.swing.GroupLayout(menuLateral);
        menuLateral.setLayout(menuLateralLayout);
        menuLateralLayout.setHorizontalGroup(
            menuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLateralLayout.createSequentialGroup()
                .addGroup(menuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelOp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(menuLateralLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(menuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(opMenu3Reportes, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(opMenu4Cierre, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(panelOp3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelOp4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(menuLateralLayout.createSequentialGroup()
                        .addContainerGap(5, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(opMenu2LibroDiario, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelOp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(menuLateralLayout.createSequentialGroup()
                        .addContainerGap(5, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(opMenu6, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelOp6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(menuLateralLayout.createSequentialGroup()
                .addGroup(menuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuLateralLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(menuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbSistemasContables, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(opMenu1Catalogo, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(opMenu5AcercaDe, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelOp5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(menuLateralLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        menuLateralLayout.setVerticalGroup(
            menuLateralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLateralLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(lbSistemasContables)
                .addGap(32, 32, 32)
                .addComponent(opMenu1Catalogo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelOp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opMenu2LibroDiario, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelOp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(opMenu3Reportes, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelOp3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opMenu4Cierre, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelOp4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opMenu6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelOp6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opMenu5AcercaDe, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelOp5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 951, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panelCopyR.setBackground(new java.awt.Color(255, 255, 255));

        lbCopyR.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbCopyR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbCopyR.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panelCopyRLayout = new javax.swing.GroupLayout(panelCopyR);
        panelCopyR.setLayout(panelCopyRLayout);
        panelCopyRLayout.setHorizontalGroup(
            panelCopyRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCopyRLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lbCopyR, javax.swing.GroupLayout.DEFAULT_SIZE, 928, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );
        panelCopyRLayout.setVerticalGroup(
            panelCopyRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCopyRLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbCopyR, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        rSLabelFecha2.setForeground(new java.awt.Color(153, 0, 0));
        rSLabelFecha2.setFont(new java.awt.Font("Roboto Bold", 1, 22)); // NOI18N

        rSLabelHora2.setForeground(new java.awt.Color(153, 0, 0));
        rSLabelHora2.setFont(new java.awt.Font("Roboto Bold", 1, 22)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCopyR, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(escritorio)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rSLabelFecha2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rSLabelHora2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rSLabelFecha2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rSLabelHora2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(escritorio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelCopyR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
        });

        opSalir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        opSalir.setForeground(new java.awt.Color(153, 0, 0));
        opSalir.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        opSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/salir.png"))); // NOI18N
        opSalir.setText("Salir");
        opSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        opSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                opSalirMousePressed(evt);
            }
        });

        lbBienvenida.setFont(new java.awt.Font("Segoe UI Black", 0, 16)); // NOI18N
        lbBienvenida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panelSalirLayout = new javax.swing.GroupLayout(panelSalir);
        panelSalir.setLayout(panelSalirLayout);
        panelSalirLayout.setHorizontalGroup(
            panelSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSalirLayout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(lbBienvenida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(153, 153, 153)
                .addComponent(opSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelSalirLayout.setVerticalGroup(
            panelSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSalirLayout.createSequentialGroup()
                .addComponent(lbBienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(opSalir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelTopLayout = new javax.swing.GroupLayout(panelTop);
        panelTop.setLayout(panelTopLayout);
        panelTopLayout.setHorizontalGroup(
            panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTopLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelTopLayout.setVerticalGroup(
            panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTopLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelTopLayout.createSequentialGroup()
                        .addComponent(panelSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(11, 11, 11)))
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(menuLateral, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menuLateral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelOp1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelOp1MousePressed
        colorDefault();
        panelOp1.setBackground(colorActivoModulo);
    }//GEN-LAST:event_panelOp1MousePressed

    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed
        ocultarMod(0);
        visible = !visible;
        menuLateral.setVisible(visible);
    }//GEN-LAST:event_jLabel3MousePressed

    private void opSalirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opSalirMousePressed
        colorDefault();
        opDefault();
//        panelSalir.setBackground(colorActivoModulo);
        Login login = new Login();
        ControladorLogin ctrl = new ControladorLogin(login);
        login.setVisible(true);

    }//GEN-LAST:event_opSalirMousePressed

    private void opMenu3ReportesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opMenu3ReportesMousePressed
        colorDefault();
        opDefault();
        ocultarMod(2);
    }//GEN-LAST:event_opMenu3ReportesMousePressed

    private void VerCatalogoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VerCatalogoMousePressed
        opDefault();
        VerCatalogo.setBackground(colorActivoOp);
        Catalogos c = new Catalogos(new JFrame(), visible);
        ControladorMostrarCatalogo ctrl = new ControladorMostrarCatalogo(c);
        c.iniciar();
    }//GEN-LAST:event_VerCatalogoMousePressed

    private void opMenu5AcercaDeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opMenu5AcercaDeMousePressed
        colorDefault();
        opDefault();
        ocultarMod(4);
    }//GEN-LAST:event_opMenu5AcercaDeMousePressed

    private void menu3Op1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu3Op1MousePressed
        opDefault();
        menu3Op1.setBackground(colorActivoOp);

        VistaBalanzaComprobacion vista = new VistaBalanzaComprobacion(new JFrame(), true);
        ControladorBalanzaC crt = new ControladorBalanzaC(vista);

        vista.setVisible(true);


    }//GEN-LAST:event_menu3Op1MousePressed

    private void panelOp3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelOp3MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_panelOp3MousePressed

    private void menu3Op2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu3Op2MousePressed
        opDefault();
        menu3Op2.setBackground(colorActivoOp);

        VistaBalanceGenerales vista = new VistaBalanceGenerales(new JFrame(), true);
        ControladorBalanceGeneral control = new ControladorBalanceGeneral(vista);
        control.setModels();
        control.iniciar();

    }//GEN-LAST:event_menu3Op2MousePressed

    private void menu3Op3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu3Op3MousePressed
        opDefault();
        menu3Op3.setBackground(colorActivoOp);

        //    ControladorEvaluarExpresion ctlEvaluarExpresion = new ControladorEvaluarExpresion(vista);
        VistaEstadoResultado v = new VistaEstadoResultado(new JFrame(), visible);
        ControladorEstadoResultado c = new ControladorEstadoResultado(v);
        v.iniciar();

    }//GEN-LAST:event_menu3Op3MousePressed

    private void opMenu4CierreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opMenu4CierreMousePressed
        colorDefault();
        opDefault();
        ocultarMod(3);
        this.menu4Op2.setEnabled(false);
        this.menu4Op3.setEnabled(false);
    }//GEN-LAST:event_opMenu4CierreMousePressed

    private void menu4Op1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu4Op1MousePressed
        // Restablecer estado por defecto de la interfaz
        opDefault();
        menu4Op1.setBackground(colorActivoOp);

        int opcion1 = JOptionPane.showConfirmDialog(
                this,
                "Para Realizar Esta Opcion Debe de Haber Generado Un Backup de La Base y Los Reportes",
                "CONFIRMAR ACCIÓN",
                JOptionPane.YES_NO_OPTION
        );

        ControladorContable ctr = new ControladorContable();
        // Comprobar qué botón presionó el usuario

        // Comprobar qué botón presionó el usuario
        if (opcion1 == JOptionPane.YES_OPTION) {
            ctr.ajustarIva(); // Llamar al método para guardar los datos
            JOptionPane.showMessageDialog(this, "Ajuste de IVA Realizado", "LISTO", JOptionPane.INFORMATION_MESSAGE);
            this.menu4Op1.setEnabled(false);
            this.menu4Op2.setEnabled(true);
            this.menu4Op3.setEnabled(false);
        } else {
            JOptionPane.showMessageDialog(this, "OPERACIÓN CANCELADA", "CANCELADO", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_menu4Op1MousePressed

    private void menu4Op2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu4Op2MousePressed
        opDefault();
        menu4Op2.setBackground(colorActivoOp);

        String input;
        boolean isValid;

        // Solicitar al usuario el inventario final
        do {
            input = JOptionPane.showInputDialog(this, "Ingrese el Inventario Final:", "Inventario Final", JOptionPane.PLAIN_MESSAGE);

            // Verificar si el usuario canceló la entrada
            if (input == null) {
                return; // El usuario canceló, se sale del método
            }

            // Validar que el input sea un número con hasta dos decimales
            isValid = input.matches("^\\d+(\\.\\d{1,2})?$");
            if (!isValid) {
                JOptionPane.showMessageDialog(this, "Por favor, ingrese un número válido con hasta dos decimales.", "Entrada no válida", JOptionPane.ERROR_MESSAGE);
            }
        } while (!isValid); // Continuar hasta que la entrada sea válida

        // Convertir el valor ingresado a double
        double inventarioFinal = Double.parseDouble(input);

        // Crear el controlador contable
        ControladorContable controlador = new ControladorContable();

        try {

            // Calcular Ventas Netas
            controlador.calcularVentasNetas();

            // Calcular Compras Totales
            controlador.calcularComprasTotales();

            // Calcular Compras Netas
            controlador.calcularComprasNetas();
            //Calcular mercaderia disponible
            controlador.calcularMercaderiaDisponible();

            //Calcular costo de ventas
            controlador.calcularCostoVentas(inventarioFinal);

            //Calcular Utilidad Bruta
            controlador.calcularUtilidadBruta();

            //Calcular Liquidar ventas
            controlador.calcularLiquidarVentas();
            //Calcular Liquidar Gastos
            controlador.calcularLiquidarGastos();
            //Calcular otros gastos
            controlador.calcularLiquidarOtrosGastos();
            //Calcular utilidad del ejercicio
            controlador.calcularUtilidadEjercicio();

            // Cerrar conexiones al finalizar
            controlador.cerrarConexiones();

        } catch (Exception e) {
            // Manejo genérico de cualquier otra excepción
            JOptionPane.showMessageDialog(this, "Ha ocurrido un error inesperado: " + e.getMessage(), "Error General", JOptionPane.ERROR_MESSAGE);
        }

        this.menu4Op2.setEnabled(false);
        this.menu4Op3.setEnabled(true);

    }//GEN-LAST:event_menu4Op2MousePressed

    private void panelOp4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelOp4MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_panelOp4MousePressed

    private void opMenu1CatalogoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opMenu1CatalogoMousePressed
        opDefault();
        VerCatalogo.setBackground(colorActivoOp);
        AgregarMayor.setBackground(colorActivoOp);
        colorDefault();
        opDefault();
        ocultarMod(1);

    }//GEN-LAST:event_opMenu1CatalogoMousePressed

    private void menu5Op1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu5Op1MousePressed
        opDefault();
        menu5Op1.setBackground(colorActivoOp);
        VistaAcercaDe frmAcerca = new VistaAcercaDe(this, visible, "© 2024 Software");
        frmAcerca.setVisible(true);
    }//GEN-LAST:event_menu5Op1MousePressed

    private void panelOp5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelOp5MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_panelOp5MousePressed
    //RESTORE DE BACKUP BD 
    private void menu6Op1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu6Op1MousePressed
        RestoreBackupDatabase restoreBackup = new RestoreBackupDatabase();
        restoreBackup.restoreBackup();
    }//GEN-LAST:event_menu6Op1MousePressed

    private void panelOp6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelOp6MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_panelOp6MousePressed

    private void opMenu6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opMenu6MousePressed
        colorDefault();
        opDefault();
        ocultarMod(5);
    }//GEN-LAST:event_opMenu6MousePressed

    private void opMenu2LibroDiarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opMenu2LibroDiarioMousePressed
        colorDefault();
        opDefault();
        ocultarMod(6);
    }//GEN-LAST:event_opMenu2LibroDiarioMousePressed

    private void menu2Op1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu2Op1MousePressed
        opDefault();
        menu2Op2.setBackground(colorActivoOp);
        VistaLibroDiario frmLibroDiario = new VistaLibroDiario(this, visible, "Libro Diario");
        ControladorLibroDiario ctrlLibro = new ControladorLibroDiario(frmLibroDiario);
        frmLibroDiario.setVisible(true);
    }//GEN-LAST:event_menu2Op1MousePressed

    private void panelOp2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelOp2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_panelOp2MousePressed

    private void AgregarMayorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarMayorMousePressed
        opDefault();
        AgregarMayor.setBackground(colorActivoOp);
        AgregarCatalogo a = new AgregarCatalogo(new JFrame(), visible);
        ControladorAgregarCatalogo c = new ControladorAgregarCatalogo(a);
        a.iniciar();
    }//GEN-LAST:event_AgregarMayorMousePressed

    private void menu2Op2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu2Op2MousePressed
        opDefault();
        menu2Op1.setBackground(colorActivoOp);

        VistaMostrarLibroDiario frmMostrar = new VistaMostrarLibroDiario(this, visible, "Partidas del Libro Diario");
        ControladorMostrarLibroDiario ctrlL = new ControladorMostrarLibroDiario(frmMostrar);
        frmMostrar.setVisible(true);
    }//GEN-LAST:event_menu2Op2MousePressed

    private void AgregarSubMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AgregarSubMousePressed
        opDefault();
        AgregarSub.setBackground(colorActivoOp);

        AgregarSubcuenta a = new AgregarSubcuenta(new JFrame(), visible);
        ControladorSubCuenta ctrl = new ControladorSubCuenta(a);
        a.iniciar();
    }//GEN-LAST:event_AgregarSubMousePressed

    private void menu3Op4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu3Op4MousePressed
        opDefault();
        menu3Op4.setBackground(colorActivoOp);

        VistaMayor frmLibroMayor = new VistaMayor(new JFrame(), true);
        ControladorLibroMayor ctrl = new ControladorLibroMayor(frmLibroMayor);
        frmLibroMayor.iniciar();
    }//GEN-LAST:event_menu3Op4MousePressed
    //CREAR EL BACKUP DE LA BASE DE DATOS SIC
    private void menu6Op2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu6Op2MousePressed
        BackupDatabase backupDatabase = new BackupDatabase();
        backupDatabase.createBackup();
    }//GEN-LAST:event_menu6Op2MousePressed

    private void menu4Op3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu4Op3MousePressed
        // TODO add your handling code here:
        ControladorContable controlador = new ControladorContable();

        try {

            controlador.calcularPartidaCierre();

            controlador.AlmacenarNuevoCiclo();

            // Cerrar conexiones al finalizar
            controlador.cerrarConexiones();

        } catch (Exception e) {
            // Manejo genérico de cualquier otra excepción
            JOptionPane.showMessageDialog(this, "Ha ocurrido un error inesperado: " + e.getMessage(), "Error General", JOptionPane.ERROR_MESSAGE);
        }


    }//GEN-LAST:event_menu4Op3MousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel AgregarMayor;
    public javax.swing.JLabel AgregarSub;
    public javax.swing.JLabel VerCatalogo;
    private javax.swing.JDesktopPane escritorio;
    public javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lbBienvenida;
    private javax.swing.JLabel lbCopyR;
    private javax.swing.JLabel lbSistemasContables;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel menu2Op1;
    private javax.swing.JLabel menu2Op2;
    private javax.swing.JLabel menu3Op1;
    private javax.swing.JLabel menu3Op2;
    private javax.swing.JLabel menu3Op3;
    private javax.swing.JLabel menu3Op4;
    private javax.swing.JLabel menu4Op1;
    private javax.swing.JLabel menu4Op2;
    private javax.swing.JLabel menu4Op3;
    private javax.swing.JLabel menu5Op1;
    private javax.swing.JLabel menu6Op1;
    private javax.swing.JLabel menu6Op2;
    private javax.swing.JPanel menuLateral;
    public javax.swing.JLabel opMenu1Catalogo;
    public javax.swing.JLabel opMenu2LibroDiario;
    public javax.swing.JLabel opMenu3Reportes;
    public javax.swing.JLabel opMenu4Cierre;
    public javax.swing.JLabel opMenu5AcercaDe;
    public javax.swing.JLabel opMenu6;
    private javax.swing.JLabel opSalir;
    private javax.swing.JPanel panelCopyR;
    public javax.swing.JPanel panelOp1;
    public javax.swing.JPanel panelOp2;
    public javax.swing.JPanel panelOp3;
    public javax.swing.JPanel panelOp4;
    public javax.swing.JPanel panelOp5;
    public javax.swing.JPanel panelOp6;
    private javax.swing.JPanel panelSalir;
    private javax.swing.JPanel panelTop;
    private rojeru_san.RSLabelFecha rSLabelFecha2;
    private rojeru_san.RSLabelHora rSLabelHora2;
    // End of variables declaration//GEN-END:variables
 public void colorDefault() {
        menuLateral.setBackground(colorMenuLateral);
        menuLateral.setForeground(colorFuente);

//        opHome.setBackground(colorDefaultModulo);
//        home.setForeground(colorFuente2);
        panelOp1.setBackground(colorDefaultModulo);
        opMenu1Catalogo.setForeground(colorFuente2);

        panelOp3.setBackground(colorDefaultModulo);
        opMenu3Reportes.setForeground(colorFuente2);

        panelOp4.setBackground(colorDefaultModulo);
        opMenu4Cierre.setForeground(colorFuente2);

        panelOp5.setBackground(colorDefaultModulo);
        opMenu5AcercaDe.setForeground(colorFuente2);

        panelOp6.setBackground(colorDefaultModulo);
        opMenu6.setForeground(colorFuente2);

        panelOp2.setBackground(colorDefaultModulo);
        opMenu2LibroDiario.setForeground(colorFuente2);

        panelSalir.setBackground(colorMenuLateral);

        opSalir.setForeground(colorFuente2);

        panelTop.setBackground(colorMenuLateral);

    }

    public void opDefault() {
//        opHome.setBackground(colorMenuLateral);
        opSalir.setBackground(colorMenuLateral);
        panelCopyR.setBackground(colorMenuLateral);
        //opciones
        VerCatalogo.setBackground(colorDefaultOp);
        AgregarMayor.setBackground(colorDefaultOp);
        AgregarSub.setBackground(colorDefaultOp);
        menu2Op1.setBackground(colorDefaultOp);
        menu2Op2.setBackground(colorDefaultOp);
        menu3Op1.setBackground(colorDefaultOp);
        menu3Op2.setBackground(colorDefaultOp);
        menu3Op3.setBackground(colorDefaultOp);
        menu3Op4.setBackground(colorDefaultOp);
        menu4Op1.setBackground(colorDefaultOp);
        menu4Op2.setBackground(colorDefaultOp);
        menu4Op3.setBackground(colorDefaultOp);
        menu5Op1.setBackground(colorDefaultOp);
        menu6Op1.setBackground(colorDefaultOp);
        menu6Op2.setBackground(colorDefaultOp);

    }

    public void color() {
        colorDefaultModulo = new Color(153, 0, 0);
        colorActivoModulo = new Color(102, 0, 0);
        colorDefaultOp = new Color(153, 0, 0);
        colorActivoOp = new Color(102, 0, 0);
        colorMenuLateral = new Color(153, 0, 0); //COLOR DE TODO EL PANEL
        colorFuente = new Color(255, 255, 255);
        colorFuente2 = new Color(255, 255, 255);
    }

    public void ocultarMod(int valor) {
        switch (valor) {
            case 0 -> {
                this.panelOp1.setVisible(false);
                this.panelOp3.setVisible(false);
                this.panelOp4.setVisible(false);
                this.panelOp5.setVisible(false);
                this.panelOp6.setVisible(false);
                this.panelOp2.setVisible(false);
                break;
            }
            case 1 -> {
                panelOp1.setBackground(colorActivoModulo);
                panelOp1.setVisible(!panelOp1.isVisible());
                this.panelOp3.setVisible(false);
                this.panelOp4.setVisible(false);
                this.panelOp5.setVisible(false);
                this.panelOp6.setVisible(false);
                this.panelOp2.setVisible(false);
                break;
            }
            case 2 -> {
                panelOp3.setBackground(colorActivoModulo);
                panelOp3.setVisible(!panelOp3.isVisible());
                this.panelOp1.setVisible(false);
                this.panelOp4.setVisible(false);
                this.panelOp5.setVisible(false);
                this.panelOp6.setVisible(false);
                this.panelOp2.setVisible(false);
                break;
            }
            case 3 -> {
                panelOp4.setBackground(colorActivoModulo);
                panelOp4.setVisible(!panelOp4.isVisible());
                this.panelOp1.setVisible(false);
                this.panelOp3.setVisible(false);
                this.panelOp5.setVisible(false);
                this.panelOp6.setVisible(false);
                this.panelOp2.setVisible(false);
                break;
            }
            case 4 -> {
                panelOp5.setBackground(colorActivoModulo);
                panelOp5.setVisible(!panelOp5.isVisible());
                this.panelOp1.setVisible(false);
                this.panelOp3.setVisible(false);
                this.panelOp4.setVisible(false);
                this.panelOp6.setVisible(false);
                this.panelOp2.setVisible(false);
                break;
            }
            case 5 -> {
                panelOp6.setBackground(colorActivoModulo);
                panelOp6.setVisible(!panelOp6.isVisible());
                this.panelOp1.setVisible(false);
                this.panelOp3.setVisible(false);
                this.panelOp4.setVisible(false);
                this.panelOp5.setVisible(false);
                this.panelOp2.setVisible(false);
                break;
            }
            case 6 -> {
                panelOp2.setBackground(colorActivoModulo);
                panelOp2.setVisible(!panelOp2.isVisible());
                this.panelOp1.setVisible(false);
                this.panelOp3.setVisible(false);
                this.panelOp4.setVisible(false);
                this.panelOp5.setVisible(false);
                this.panelOp6.setVisible(false);
                break;
            }

        }

    }

    public void copyright() {

        this.lbCopyR.setMaximumSize(panelCopyR.getMaximumSize());
        this.lbCopyR.setForeground(colorFuente2);
        this.lbCopyR.setText("Sistemas Contables © UES 2024");
    }

    public void config() {
        colorDefault();
        opDefault();
        copyright();
        menuLateral.setVisible(visible);
//        opHome.setVisible(true);
        opSalir.setVisible(true);
        this.escritorio.setBorder(new Fondo("/img/fondo.jpg"));
        lbSistemasContables.setText("Sistemas Contables");
        lbBienvenida.setText("Bienvenido al Sistema");
        lbBienvenida.setForeground(colorFuente2);

    }

    public void panels() {
        panelOp1.setVisible(false);
        panelOp3.setVisible(false);
        panelOp4.setVisible(false);
        panelOp5.setVisible(false);
        panelOp6.setVisible(false);
        panelOp2.setVisible(false);

    }
}
